version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - api-gateway
    networks:
      - ecommerce_network

  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - order-service
      - payment-service
    networks:
      - ecommerce_network

  order-service:
    build: ./order-service
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq-host:5672/
    depends_on:
      - orders_db
      - rabbitmq
    networks:
      - ecommerce_network

  orders_db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - orders_data:/var/lib/postgresql/data
    networks:
      - ecommerce_network
    depends_on:
      - rabbitmq

  payment-service:
    build: ./payment-service
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq-host:5672/
    depends_on:
      - payments_db
      - rabbitmq
    networks:
      - ecommerce_network

  payments_db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - payments_data:/var/lib/postgresql/data
    networks:
      - ecommerce_network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    container_name: rabbitmq  # Явное имя контейнера
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 10s
      retries: 30
    networks:
      ecommerce_network:
        aliases:
          - rabbitmq-host

volumes:
  orders_data:
  payments_data:
  rabbitmq_data:

networks:
  ecommerce_network:
    name: ecommerce_network
    driver: bridge
    attachable: true